// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ECommerceWebAPI
{
    public partial class CartItem
    {
        [Key]
        [Column("User_ID")]
        public int UserId { get; set; }
        [Key]
        [Column("Product_ID")]
        public int ProductId { get; set; }
        public int? Quantity { get; set; }

        [ForeignKey(nameof(ProductId))]
        [InverseProperty("CartItems")]
        public virtual Product Product { get; set; }
        [ForeignKey(nameof(UserId))]
        [InverseProperty("CartItems")]
        public virtual User User { get; set; }
    }
}